// libnetstack.h - C interface for Go netstack
//
// This header is generated by `go build -buildmode=c-archive`.
// This placeholder allows Swift to compile before the Go library is built.
// Run `make` in Sources/OmertaTunnel/Netstack to generate the real header.

#ifndef LIBNETSTACK_H
#define LIBNETSTACK_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// Callback type for returning packets to Swift
typedef void (*ReturnPacketCallback)(void* context, const uint8_t* data, size_t len);

// Create a new netstack instance
// Returns a handle (>0) on success, 0 on failure
// gatewayIP should be like "10.200.0.1"
extern uint64_t NetstackCreate(const char* gatewayIP, uint32_t mtu);

// Set the callback for returning packets
// context is passed back to the callback
extern void NetstackSetCallback(uint64_t handle, ReturnPacketCallback callback, void* context);

// Start the netstack processing
// Returns 0 on success, -1 on error
extern int NetstackStart(uint64_t handle);

// Stop and destroy the netstack instance
extern void NetstackStop(uint64_t handle);

// Inject a raw IP packet into the stack
// Returns 0 on success, -1 on error
extern int NetstackInjectPacket(uint64_t handle, const uint8_t* data, size_t len);

// Get statistics about the stack
// Returns 0 on success, -1 on error
extern int NetstackGetStats(uint64_t handle, uint32_t* tcpConns, uint32_t* udpConns);

#ifdef __cplusplus
}
#endif

#endif // LIBNETSTACK_H
