stateDiagram-v2
    [*] --> WAITING_FOR_LOCK
    SESSION_ABORTED --> [*]
    WAITING_FOR_LOCK --> VM_PROVISIONING : start_session
    VM_PROVISIONING --> SESSION_ABORTED : timeout(VM_ALLOCATION_TIMEOUT)
    VM_PROVISIONING --> NOTIFYING_CABAL : allocate_vm
    NOTIFYING_CABAL --> WAITING_FOR_VERIFICATION : [auto]
    WAITING_FOR_VERIFICATION --> WAITING_FOR_VERIFICATION : VM_CONNECTIVITY_VOTE
    WAITING_FOR_VERIFICATION --> VM_RUNNING : [auto]\n[LENGTH (connectivity_votes) >=...]
    WAITING_FOR_VERIFICATION --> SENDING_CANCELLATION : [auto]\n[LENGTH (connectivity_votes) >=...]
    WAITING_FOR_VERIFICATION --> VM_RUNNING : timeout(CONNECTIVITY_CHECK_TIMEOUT)\n[LENGTH (connectivity_votes) > ...]
    WAITING_FOR_VERIFICATION --> SENDING_CANCELLATION : timeout(CONNECTIVITY_CHECK_TIMEOUT)\n[LENGTH (connectivity_votes) ==...]
    VM_RUNNING --> HANDLING_CANCEL : CANCEL_REQUEST\n[message.sender == LOAD (consum...]
    VM_RUNNING --> HANDLING_CANCEL : cancel_session
    HANDLING_CANCEL --> SENDING_CANCELLATION : [auto]
    SENDING_CANCELLATION --> WAITING_FOR_ATTESTATION : [auto]
    WAITING_FOR_ATTESTATION --> SESSION_COMPLETE : ATTESTATION_RESULT