stateDiagram-v2
    [*] --> AWAITING_ALLOCATION
    DONE --> [*]
    AWAITING_ALLOCATION --> AWAITING_ALLOCATION : setup_session
    AWAITING_ALLOCATION --> VERIFYING_VM : VM_ALLOCATED
    VERIFYING_VM --> COLLECTING_VOTES : [auto]
    COLLECTING_VOTES --> COLLECTING_VOTES : VM_CONNECTIVITY_VOTE\n[message.payload.witness != pee...]
    COLLECTING_VOTES --> EVALUATING_CONNECTIVITY : [auto]\n[LENGTH (connectivity_votes) >=...]
    COLLECTING_VOTES --> EVALUATING_CONNECTIVITY : timeout(CONNECTIVITY_VOTE_TIMEOUT)
    EVALUATING_CONNECTIVITY --> MONITORING : [auto]\n[LENGTH (connectivity_votes) > ...]
    EVALUATING_CONNECTIVITY --> VOTING_ABORT : [auto]\n[LENGTH (connectivity_votes) ==...]
    MONITORING --> ATTESTING : VM_CANCELLED
    MONITORING --> HANDLING_MISUSE : MISUSE_ACCUSATION
    HANDLING_MISUSE --> VOTING_ABORT : [auto]\n[LOAD (misuse_accusation).evide...]
    HANDLING_MISUSE --> MONITORING : [auto]\n[LOAD (misuse_accusation).evide...]
    VOTING_ABORT --> COLLECTING_ABORT_VOTES : [auto]
    COLLECTING_ABORT_VOTES --> COLLECTING_ABORT_VOTES : ABORT_VOTE\n[message.payload.witness != pee...]
    COLLECTING_ABORT_VOTES --> ATTESTING : [auto]\n[LENGTH (abort_votes) / (LENGTH...]
    COLLECTING_ABORT_VOTES --> MONITORING : timeout(ABORT_VOTE_TIMEOUT)\n[LENGTH (abort_votes) / (LENGTH...]
    COLLECTING_ABORT_VOTES --> ATTESTING : timeout(ABORT_VOTE_TIMEOUT)\n[LENGTH (abort_votes) / (LENGTH...]
    ATTESTING --> COLLECTING_ATTESTATION_SIGS : [auto]
    COLLECTING_ATTESTATION_SIGS --> COLLECTING_ATTESTATION_SIGS : ATTESTATION_SHARE
    COLLECTING_ATTESTATION_SIGS --> PROPAGATING_ATTESTATION : [auto]\n[LENGTH (attestation_signatures...]
    PROPAGATING_ATTESTATION --> DONE : [auto]