/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/omerta/tunnel-netstack/cmd */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <stdint.h>

// Callback type for returning packets to Swift
typedef void (*ReturnPacketCallback)(void* context, const uint8_t* data, size_t len);

// Helper function to invoke the callback (can't call function pointers directly from Go)
static inline void invokeCallback(ReturnPacketCallback cb, void* ctx, const uint8_t* data, size_t len) {
    if (cb != NULL) {
        cb(ctx, data, len);
    }
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// NetstackCreate creates a new netstack instance.
// Returns a handle (>0) on success, 0 on failure.
// gatewayIP should be like "10.200.0.1"
extern uint64_t NetstackCreate(char* gatewayIP, uint32_t mtu);

// NetstackSetCallback sets the callback for returning packets.
// context is passed back to the callback (typically a Swift object pointer).
extern void NetstackSetCallback(uint64_t handle, ReturnPacketCallback callback, void* context);

// NetstackStart starts the netstack processing.
extern int NetstackStart(uint64_t handle);

// NetstackStop stops and destroys the netstack instance.
extern void NetstackStop(uint64_t handle);

// NetstackInjectPacket injects a raw IP packet into the stack.
// Returns 0 on success, -1 on error.
extern int NetstackInjectPacket(uint64_t handle, uint8_t* data, size_t len);

// NetstackGetStats returns statistics about the stack.
// Writes to the provided pointers.
extern int NetstackGetStats(uint64_t handle, uint32_t* tcpConns, uint32_t* udpConns);

// NetstackDialTCP creates a TCP connection to the specified host:port through the stack.
// Returns a connection handle (>0) on success, 0 on failure.
extern uint64_t NetstackDialTCP(uint64_t stackHandle, char* host, uint16_t port);

// NetstackConnRead reads data from a TCP connection.
// Returns number of bytes read, 0 on EOF, -1 on error.
extern int NetstackConnRead(uint64_t connHandle, uint8_t* buf, size_t maxLen);

// NetstackConnWrite writes data to a TCP connection.
// Returns number of bytes written, -1 on error.
extern int NetstackConnWrite(uint64_t connHandle, uint8_t* buf, size_t len);

// NetstackConnClose closes a TCP connection.
extern void NetstackConnClose(uint64_t connHandle);

// NetstackConnSetReadDeadline sets the read deadline in milliseconds from now.
// Use 0 to clear the deadline.
extern int NetstackConnSetReadDeadline(uint64_t connHandle, int64_t milliseconds);

// NetstackConnSetWriteDeadline sets the write deadline in milliseconds from now.
// Use 0 to clear the deadline.
extern int NetstackConnSetWriteDeadline(uint64_t connHandle, int64_t milliseconds);

#ifdef __cplusplus
}
#endif
